# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-r", "web-applications/"]
  - repo: local
    hooks:
      - id: quality-check
        name: multi-stack-quality-check
        entry: python packages/code-quality-checking/quality-check.py --mode epic
        language: system
        pass_filenames: false
        always_run: true
