/**
 * Shared Command Mapping
 *
 * Maps framework actions to recommended commands.
 * Synced with BOB_COMMANDS_MAPPING_TABLE.md
 */

export function getRecommendedCommands(action: string): string[] {
  const map: Record<string, string[]> = {
    validate_repository_structure: ['npm run start -- framework-test'],
    validate_framework_version: ['npm run start -- framework-test'],
    run_framework_diagnostics: ['npm run start -- framework-test'],
    install_framework_dependencies: ['npm install'],
    validate_environment: ['npm run start -- framework-test'],
    run_framework_tests: ['npm run start -- framework-test'],
    generate_health_report: ['npm run start -- framework-test'],
    start_engine_services: ['npm run start -- framework-start'],
    start_watchdog_service: ['npm run start -- framework-start'],
    start_project_init: ['npm run start -- project-init --type new'],
    prompt_project_type: ['npm run start -- project-init --type new'],
    validate_framework_project_alignment: ['npm run start -- overview'],
    generate_tech_stack: ['npm run start -- overview'],
    generate_project_context: ['npm run start -- overview'],
    generate_project_management_structure: ['npm run start -- overview'],
    generate_vision_document: ['npm run start -- overview'],
    user_review_vision: ['/review-design'],
    generate_user_flow: ['/init-project'],
    validate_user_flow: ['/check-implementation'],
    generate_requirements: ['/review-requirements'],
    generate_design_bible: ['/init-project'],
    approve_design_bible: ['/review-design'],
    generate_architecture_design: ['npm run start -- architecture'],
    validate_tech_stack: ['npm run start -- overview'],
    generate_database_schema: ['npm run start -- overview'],
    generate_api_contracts: ['npm run start -- overview'],
    generate_epics: ['/scope-epic'],
    review_epics: ['/review-requirements'],
    generate_tickets: ['/update-planning'],
    validate_tickets: ['/check-implementation'],
    generate_project_timeline: ['npm run start -- overview'],
    select_next_ticket: ['npm run start -- next'],
    generate_code: ['npm run start -- context T-001'],
    review_code: ['/code-review'],
    generate_unit_tests: ['/writing-test'],
    run_tests: ['npm run start -- framework-test'],
    run_integration_tests: ['npm run start -- framework-test'],
    fix_bugs: ['/debug'],
    update_documentation: ['/capture-knowledge'],
    validate_epic: ['/check-implementation'],
    run_system_tests: ['npm run start -- framework-test'],
    run_performance_tests: ['npm run start -- framework-test'],
    run_security_audit: ['npm run start -- framework-test'],
    build_release_candidate: ['npm run start -- framework-test'],
    setup_continue_project_uat: ['/uat-phase'],
    setup_uat_environment: ['/uat-phase'],
    run_uat: ['/uat-phase'],
    collect_uat_feedback: ['/uat-phase'],
    fix_uat_bugs: ['/debug'],
    release_notes_generation: ['npm run start -- overview'],
    deployment_script_generation: ['npm run start -- overview'],
    rollback_plan_creation: ['npm run start -- overview'],
    deployment_checklist_generation: ['npm run start -- overview'],
    pre_launch_validation: ['npm run start -- framework-test'],
    production_deployment: ['npm run start -- framework-test'],
    deployment_verification: ['npm run start -- framework-test'],
    monitoring_setup: ['npm run start -- framework-test'],
    error_tracking_setup: ['npm run start -- framework-test'],
    performance_monitoring: ['npm run start -- framework-test'],
    ceo_product_audit: ['/plan-ceo-review'],
    eng_arch_audit: ['/plan-eng-review'],
    eng_epic_audit: ['/plan-eng-review'],
    eng_pi_readiness_audit: ['/plan-eng-review'],
    ship_epic: ['/ship'],
    expert_code_review: ['/review'],
    visual_regression_qa: ['/qa'],
    epic_retrospective: ['/retro'],
    interactive_ui_verification: ['/browse'],
    import_browser_sessions: ['/setup-browser-cookies']
  };

  return map[action] || [];
}
