import * as path from 'path';
import * as fs from 'fs-extra';
import { execSync } from 'child_process';
import { StateManager } from '../state_manager';
import { BobConfig } from '../shared/config';

export class DesignAgent {
  private pythonPath: string = 'python3';
  private skillPath: string;

  constructor() {
    const config = BobConfig.getInstance();
    // Assuming the skill is installed/linked at a known location
    this.skillPath = path.join(config.getRootDir(), 'skills-library/patterns/frontend/ui-ux-pro-max');
    
    // Check if python3 is available, fallback to python on windows if needed
    try {
      execSync('python3 --version', { stdio: 'ignore' });
    } catch (e) {
      this.pythonPath = 'python';
    }
  }

  async generateDesignFile(ticketId: string): Promise<string> {
    console.log(`🎨 DesignAgent generating UI/UX spec for ticket: ${ticketId}`);

    const ticketPath = await StateManager.getTicketPath(ticketId);
    if (!ticketPath) {
      throw new Error(`Ticket ${ticketId} not found in state.`);
    }

    const ticketDir = path.dirname(ticketPath);
    const designDir = path.join(ticketDir, 'design');
    const outputPath = path.join(designDir, 'DESIGN.md');

    // Ensure design directory exists
    await fs.ensureDir(designDir);

    // Prefer ticket title from metadata if available
    const metadataPath = path.join(path.dirname(ticketPath), 'metadata.json');
    const prdPath = path.join(path.dirname(ticketDir), 'PRD.md');
    let query = ticketId;
    if (await fs.pathExists(metadataPath)) {
      const metadata = await fs.readJson(metadataPath);
      if (metadata.title) {
        // Strip out file links and special formatting for the query
        query = metadata.title.replace(/\[.*?\]\(.*?\)/g, '').replace(/[\\#*`]/g, '').trim();
      }
    } else if (await fs.pathExists(prdPath)) {
      const prdContent = await fs.readFile(prdPath, 'utf8');
      const match = prdContent.match(/# (.*)/);
      if (match) query = match[1];
    }
    try {
      const searchScript = path.join(this.skillPath, 'scripts/search.py');
      
      // Run the reasoning engine
      const command = `"${this.pythonPath}" "${searchScript}" "${query}" --design-system -f markdown`;
      console.log(`   Executing reasoning engine: ${command}`);
      
      const designSpec = execSync(command, { encoding: 'utf8' });

      // Hierarchical Synthesis
      const mockTokens = await this.extractMockTokens(ticketId);
      const styleTokens = await this.extractStyleGuideTokens();
      const synthesizedSpec = this.synthesizeDesignSpec(designSpec, mockTokens, styleTokens);

      let finalContent = `# DESIGN: ${ticketId} UI/UX Specification\n\n`;
      finalContent += `> Automatically generated by DesignAgent using UI-UX Pro Max Reasoning Engine.\n\n`;
      finalContent += synthesizedSpec;

      await fs.writeFile(outputPath, finalContent);
      console.log(`   DESIGN.md generated at: ${outputPath}`);
      
      return outputPath;
    } catch (error: any) {
      console.error(`❌ DesignAgent failed: ${error.message}`);
      // Fallback template if script fails
      const fallback = this.generateFallbackDesign(ticketId);
      await fs.writeFile(outputPath, fallback);
      return outputPath;
    }
  }

  private async extractMockTokens(ticketId: string): Promise<Record<string, string>> {
    const tokens: Record<string, string> = {};
    const metadataPath = await StateManager.getTicketPath(ticketId);
    if (!metadataPath) return tokens;

    const metadata = await fs.readJson(metadataPath);
    const title = metadata.title || '';
    
    // Find linked HTML files in title
    const mockLinks = title.match(/file:\/\/\/(.*?\.html)/g);
    if (!mockLinks) return tokens;

    for (const link of mockLinks) {
      const filePath = link.replace('file:///', '').replace(/\//g, path.sep);
      if (await fs.pathExists(filePath)) {
        const content = await fs.readFile(filePath, 'utf8');
        
        // Extract Tailwind colors
        const colorMatch = content.match(/"primary":\s*"(#.*)"/);
        if (colorMatch) tokens['primary'] = colorMatch[1];
        
        const secondaryMatch = content.match(/"secondary":\s*"(#.*)"/);
        if (secondaryMatch) tokens['secondary'] = secondaryMatch[1];

        const bgLightMatch = content.match(/"background-light":\s*"(#.*)"/);
        if (bgLightMatch) tokens['background'] = bgLightMatch[1];

        // Extract fonts
        const fontMatch = content.match(/"display":\s*\["(.*?)",/);
        if (fontMatch) tokens['heading'] = fontMatch[1];
      }
    }

    return tokens;
  }

  private async extractStyleGuideTokens(): Promise<Record<string, string>> {
    const tokens: Record<string, string> = {};
    const config = BobConfig.getInstance();
    const styleGuideDir = path.join(config.getRootDir(), 'web-applications/project-management/design');
    const jsonPath = path.join(styleGuideDir, 'style_guide.json');
    const mdPath = path.join(styleGuideDir, 'style_guide.md');

    // Priority 1: Machine-readable JSON
    if (await fs.pathExists(jsonPath)) {
      try {
        const data = await fs.readJson(jsonPath);
        if (data.colors?.primary) tokens['primary'] = data.colors.primary;
        if (data.colors?.secondary) tokens['secondary'] = data.colors.secondary;
        if (data.typography?.heading) tokens['heading'] = data.typography.heading;
        console.log(`   Tokens extracted from: style_guide.json`);
        return tokens; // Prefer JSON if it exists and is valid
      } catch (e) {
        console.warn(`   Failed to parse style_guide.json, falling back to .md`);
      }
    }

    // Priority 2: Traditional Markdown
    if (await fs.pathExists(mdPath)) {
      const content = await fs.readFile(mdPath, 'utf8');
      
      const primaryMatch = content.match(/Primary.*?(#[0-9a-fA-F]{6})/i);
      if (primaryMatch) tokens['primary'] = primaryMatch[1];

      const secondaryMatch = content.match(/Secondary.*?(#[0-9a-fA-F]{6})/i);
      if (secondaryMatch) tokens['secondary'] = secondaryMatch[1];

      const headingMatch = content.match(/Headings.*?(_|\*\*)(\w+)(_|\*\*)/);
      if (headingMatch) tokens['heading'] = headingMatch[2];
      
      console.log(`   Tokens extracted from: style_guide.md`);
    }

    return tokens;
  }

  private synthesizeDesignSpec(spec: string, mockTokens: Record<string, string>, styleTokens: Record<string, string>): string {
    let synthesized = spec;
    const sources: string[] = [];

    // Prioritize Mock > Style Guide > Pro-Max
    const primary = mockTokens['primary'] || styleTokens['primary'];
    const secondary = mockTokens['secondary'] || styleTokens['secondary'];
    const background = mockTokens['background'] || styleTokens['background'];
    const heading = mockTokens['heading'] || styleTokens['heading'];

    if (mockTokens['primary']) sources.push('Linked Mockup (Primary Color)');
    else if (styleTokens['primary']) sources.push('Style Guide (Primary Color)');

    if (mockTokens['heading']) sources.push('Linked Mockup (Typography)');
    else if (styleTokens['heading']) sources.push('Style Guide (Typography)');

    // Inject tokens into the Markdown Spec
    if (primary) synthesized = synthesized.replace(/\| Primary \| #\w+ \|/g, `| Primary | ${primary} |`);
    if (secondary) synthesized = synthesized.replace(/\| Secondary \| #\w+ \|/g, `| Secondary | ${secondary} |`);
    if (background) synthesized = synthesized.replace(/\| Background \| #\w+ \|/g, `| Background | ${background} |`);
    if (heading) synthesized = synthesized.replace(/- \*\*Heading:\*\* \w+/g, `- **Heading:** ${heading}`);

    if (sources.length > 0) {
      synthesized = `> **Style Attribution:**\n${sources.map(s => `> - 🎨 ${s}`).join('\n')}\n\n${synthesized}`;
    }

    return synthesized;
  }

  private generateFallbackDesign(ticketId: string): string {
    return `# DESIGN: ${ticketId} UI/UX Specification (Fallback)

> Reasoning engine failed to execute. Using architectural defaults.

## 1. Design Principles
- Follow the global Design Bible.
- Use established component tokens.
- Ensure WCAG AA accessibility.

## 2. Component Requirements
- TBD: Define UI components based on implementation needs.

*Note: Please run the reasoning engine manually if possible.*
`;
  }

  /**
   * Generates 3 distinct design directions for the project level Design Bible.
   * Leverages ui-ux-pro-max reasoning engine.
   */
  async generateProjectBibleDirections(
    query: string, 
    domain: string = 'web',
    flavors?: { name: string, prompt: string }[]
  ): Promise<any[]> {
    console.log(`🎨 DesignAgent generating Design Bible directions for: ${query} (Domain: ${domain})`);
    
    const directions: any[] = [];
    const searchScript = path.join(this.skillPath, 'scripts/search.py');
    
    // Default flavors if none provided
    const activeFlavors = flavors || [
      { name: "Direction A", prompt: `--modern --minimal` },
      { name: "Direction B", prompt: `--vibrant --dynamic` },
      { name: "Direction C", prompt: `--trustworthy --classic` }
    ];

    for (let i = 0; i < activeFlavors.length; i++) {
      const flavor = activeFlavors[i];
      try {
        // Ensure prompt has modifiers and the query
        const fullPrompt = flavor.prompt.includes(query) ? flavor.prompt : `${query} ${flavor.prompt}`;
        const command = `"${this.pythonPath}" "${searchScript}" "${fullPrompt}" --domain ${domain} --design-system -f markdown`;
        console.log(`   Executing reasoning engine for ${flavor.name}: ${command}`);
        const designSpec = execSync(command, { encoding: 'utf8' });
        
        // Extract basic tokens from the generated spec (Simulated extraction)
        const primaryMatch = designSpec.match(/\| Primary \| (#[0-9a-fA-F]{6}) \|/);
        const secondaryMatch = designSpec.match(/\| Secondary \| (#[0-9a-fA-F]{6}) \|/);
        
        directions.push({
          id: i + 1,
          name: flavor.name,
          description: `A ${flavor.name} approach focusing on ${flavor.prompt.split('--')[1]} aesthetics.`,
          tokens: {
            primary: primaryMatch ? primaryMatch[1] : '#6366f1',
            secondary: secondaryMatch ? secondaryMatch[1] : '#f43f5e',
            heading: 'Inter',
            body: 'Roboto'
          },
          full_spec: designSpec
        });
      } catch (error) {
        console.warn(`   Failed to generate direction ${flavor.name}, using fallback.`);
        directions.push({
          id: i + 1,
          name: flavor.name,
          description: "Fallback direction due to reasoning engine error.",
          tokens: { primary: '#cccccc', secondary: '#999999', heading: 'sans-serif', body: 'serif' },
          full_spec: "Reasoning engine failed."
        });
      }
    }

    return directions;
  }
}
