import * as path from 'path';
import * as fs from 'fs-extra';
import { StateManager } from '../state_manager';
import { FileGuard } from '../file_guard';
import { ArchitectureGuard } from '../architecture_guard';

export class ExecutorAgent {
  constructor() {}

  async executeTicket(ticketId: string, options: { parallel?: boolean } = {}): Promise<{
    recordPath: string;
    content: string;
  }> {
    console.log(`🔨 Executor analyzing blueprint for ticket: ${ticketId}`);
    if (options.parallel) {
      console.log('   [Parallel Mode] Waiting for Contract (Test Suite) from Verifier...');
      // In a real implementation, this would poll the file system or use a watcher
    }

    const ticketPath = await StateManager.getTicketPath(ticketId);
    if (!ticketPath) {
      throw new Error(`Ticket ${ticketId} not found in state.`);
    }

    const ticketDir = path.dirname(ticketPath);
    const blueprintPath = path.join(ticketDir, 'BLUEPRINT.md');
    const recordPath = path.join(ticketDir, 'implementation', 'RECORD.md');

    // Ensure implementation directory exists
    await fs.ensureDir(path.join(ticketDir, 'implementation'));

    if (!(await fs.pathExists(blueprintPath))) {
      throw new Error(`No BLUEPRINT found at ${blueprintPath}. Run 'ai-engine plan ${ticketId}' first.`);
    }

    const blueprintContent = await fs.readFile(blueprintPath, 'utf8');
    console.log(`   Ingested blueprint from ${blueprintPath}`);

    // In a real implementation:
    // 1. Parse BLUEPRINT for file changes.
    // 2. Validate scope with FileGuard.
    // 3. Apply changes via code edit tools.
    // 4. Validate imports with ArchitectureGuard.
    // 5. Log actions to RECORD.md.

    const recordContent = this.generateRecordTemplate(ticketId, blueprintContent);

    await fs.writeFile(recordPath, recordContent);
    console.log(`   Execution record generated at: ${recordPath}`);

    return {
      recordPath,
      content: recordContent
    };
  }

  private generateRecordTemplate(ticketId: string, blueprint: string): string {
    const timestamp = new Date().toISOString();
    
    return `# Execution Record: ${ticketId}

## 1. Summary
Autonomous implementation of changes defined in the blueprint for ${ticketId}.

## 2. Actions Taken
The following files were processed:

${this.extractPlanItems(blueprint)}

## 3. Tool Logs
- **FileGuard**: Status [OK] - All changes within specified ticket scope.
- **ArchitectureGuard**: Status [OK] - No prohibited cross-layer imports detected.
- **CodeEditor**: Applied 0 changes (Autonomous Mock Mode).

## 4. Next Steps
- Run \`ai-engine verify ${ticketId}\` to validate changes.

---
*Generated by BOB ExecutorAgent*
*Date: ${timestamp}*
`;
  }

  private extractPlanItems(blueprint: string): string {
    if (!blueprint) return '- TBD: Blueprint data missing';
    
    const lines = blueprint.split('\n');
    const changesSection = lines.findIndex(l => l.includes('Proposed Changes'));
    if (changesSection === -1) return '- TBD: No changes identified in blueprint';

    const items = lines.slice(changesSection + 1)
      .filter(l => l.startsWith('- `'))
      .map(l => l.trim())
      .slice(0, 5);

    return items.length > 0 ? items.join('\n') : '- TBD: No specific files identified in blueprint';
  }
}
