import * as path from 'path';
import * as fs from 'fs-extra';
import { StateManager } from '../state_manager';
import { BobConfig } from '../shared/config';
import { ContextBuilder } from '../repo_intelligence/context';
import { SearchService } from '../repo_intelligence/search';
import { EmbeddingService } from '../repo_intelligence/embeddings';
import { RepoStorage } from '../repo_intelligence/storage';
import { PatternDetector } from '../repo_intelligence/patterns';

export class PlannerAgent {
  private contextBuilder: ContextBuilder;
  private storage: RepoStorage;

  constructor(dataPath?: string) {
    const config = BobConfig.getInstance();
    const defaultDataPath = path.join(config.getRootDir(), 'web-applications/repo_data');
    this.storage = new RepoStorage(dataPath || defaultDataPath);
    const embeddings = new EmbeddingService();
    const search = new SearchService(embeddings, this.storage);
    const patterns = new PatternDetector(this.storage);
    this.contextBuilder = new ContextBuilder(search, patterns, this.storage);
  }

  async planTicket(ticketId: string): Promise<{
    blueprintPath: string;
    content: string;
  }> {
    console.log(`🏗️  Planner analyzing ticket: ${ticketId}`);

    const ticketPath = await StateManager.getTicketPath(ticketId);
    if (!ticketPath) {
      throw new Error(`Ticket ${ticketId} not found in state.`);
    }

    const ticketDir = path.dirname(ticketPath);
    const researchPath = path.join(ticketDir, 'RESEARCH.md');
    const blueprintPath = path.join(ticketDir, 'BLUEPRINT.md');

    let researchContent = '';
    if (await fs.pathExists(researchPath)) {
      researchContent = await fs.readFile(researchPath, 'utf8');
      console.log(`   Found research data in ${researchPath}`);
    } else {
      console.warn(`⚠️  No RESEARCH.md found for ${ticketId}. Planning with limited context.`);
    }

    // In a real implementation, we would call an LLM here with:
    // 1. System Prompt (.agent/agents/planner/system-prompt.md)
    // 2. PRD.md
    // 3. RESEARCH.md
    // 4. Ticket Metadata
    
    // For now, we generate a high-quality template based on the framework's standards
    const blueprintContent = this.generateBlueprintTemplate(ticketId, researchContent);

    await fs.writeFile(blueprintPath, blueprintContent);
    console.log(`   Blueprint generated at: ${blueprintPath}`);

    return {
      blueprintPath,
      content: blueprintContent
    };
  }

  private generateBlueprintTemplate(ticketId: string, research: string): string {
    const timestamp = new Date().toISOString();
    
    return `# Blueprint: ${ticketId} Design Specification

## 1. Objective
Detailed technical plan for implementing ${ticketId}.

## 2. Proposed Changes
Based on research findings, the following files and components will be modified:

${this.extractRelevantFiles(research)}

## 3. Implementation Steps (Breaths)

### Breath 1: Data Model & Schema
- Define necessary database changes or model attributes.
- Ensure alignment with Supabase/PostgreSQL standards.

### Breath 2: Service Layer & Business Logic
- Implement core logic in the appropriate service classes.
- Follow the Repository pattern if applicable.

### Breath 3: API & Controller Interface
- Expose functionality via RESTful endpoints.
- Ensure proper request/response validation.

### Breath 4: Frontend Integration (if applicable)
- Update UI components to reflect backend changes.
- Ensure consistent styling with the Design Bible.

## 4. Verification Plan
- [ ] Unit tests for new service logic.
- [ ] Integration tests for API endpoints.
- [ ] Manual UI verification (if applicable).

---
*Generated by BOB PlannerAgent*
*Date: ${timestamp}*
`;
  }

  private extractRelevantFiles(research: string): string {
    if (!research) return '- TBD: Research data missing';
    
    // Simple extraction of files from RESEARCH.md format
    const lines = research.split('\n');
    const filesSection = lines.findIndex(l => l.includes('Relevant Files'));
    if (filesSection === -1) return '- TBD: No files identified in research';

    const files = lines.slice(filesSection + 1)
      .filter(l => l.startsWith('- `'))
      .map(l => l.trim())
      .slice(0, 5);

    return files.length > 0 ? files.join('\n') : '- TBD: No specific files identified';
  }

  close(): void {
    this.storage.close();
  }
}
